RTech.Demo/Areas/Student/ViewModels/SignUpViewModel.cs
using Riddhasoft.Student.Entity;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;


namespace RTech.Demo.Areas.Student.ViewModels
{
    public class SignUpViewModel
    {
        public int Id { get; set; }

        public Institute Institute { get; set; }

        [Required, Display(Name = "First Name")]
        public string FirstName { get; set; }

        //public string MiddleName { get; set; }

        [Required, Display(Name = "Last Name")]
        public string LastName { get; set; }

        public string ImageUrl { get; set; }

        [Required]
        public string Address { get; set; }

        [Required, Display(Name = "Phone Number")]
        public string PhoneNumber { get; set; }

        [RegularExpression(@"^([\w\.\-]+)@([\w\-]+)((\.(\w){2,3})+)$", ErrorMessage = "Please enter valid email")]
        [Required, DataType(DataType.EmailAddress , ErrorMessage ="Valid Email Address is Requires")]
        public string Email { get; set; }

        public Gender Gender { get; set; }

        [Required]
        public string BirthCountry { get; set; }

        [Required]
        public string Occupation { get; set; }

        //[Required]
        //public string Username { get; set; }

        [Required, StringLength(15,MinimumLength =7)]
        public string Password { get; set; }

        [DataType(DataType.Password), Compare("Password")]
        public string ConfirmPassword { get; set; }
        public bool AgreeTermsAndConditions { get; set; }
    }


}

RTech.Demo/Areas/Student/Controllers/SignUpController.cs
using Riddhasoft.Services.Common;
using Riddhasoft.Setup.Entity;
using Riddhasoft.Setup.Services;
using Riddhasoft.Student.Entity;
using Riddhasoft.Student.Services;
using RTech.Demo.Areas.EmailTemplete.ViewModels;
using RTech.Demo.Areas.Student.ViewModels;
using RTech.Demo.Common;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Text.RegularExpressions;
using System.Threading;
using System.Web;
using System.Web.Configuration;
using System.Web.Mvc;
using System.Web.Mvc.Html;


namespace RTech.Demo.Areas.Student.Controllers
{
    public class SignUpController : Controller
    {
        SStudentInformation _studentInformationService = null;
        SStudentLogin _studentLoginService = new SStudentLogin();
        CommonServices _commonService = new CommonServices();

        public SignUpController()
        {
            _studentInformationService = new SStudentInformation();

        }
        // GET: Student/SignUp
        public ActionResult Index()
        {
            if (Common.StudentSession.LoggedStudent != null)
            {
                return RedirectToAction("Index", "Dashboard");
            }

            SetViewBagForCountries();
            return View();
        }

        [HttpPost]
        public ActionResult Index(SignUpViewModel model)
        {
            var countries = _commonService.getCountryDropDown();
            ViewBag.Countries = new SelectList(countries, "CountryCode", "Country");
            if (ModelState.IsValid)
            {
                bool valid = true;

                ServiceResult<bool> isUiqueEmail = _studentInformationService.IsEmailExist(model.Email);
                if (isUiqueEmail.Data == false)
                {
                    ModelState.AddModelError("Email", isUiqueEmail.Message);
                    valid = false;
                }

                if (valid == true)
                {

                    if (Request.Files.Count > 0)
                    {
                        string fileName = "";
                        string directory = Server.MapPath("/Images");
                        var image = Request.Files["image"];

                        if (image != null && image.ContentLength > 0)
                        {
                            fileName = Guid.NewGuid() + "." + image.FileName.Split('.')[1];
                            image.SaveAs(Path.Combine(directory, fileName));
                            model.ImageUrl = "/Images/" + fileName;
                        }
                    }

                    EStudentInformation data = new EStudentInformation()
                    {
                        Institute = model.Institute,
                        FirstName = model.FirstName,
                        LastName = model.LastName,
                        PhoneNumber = model.PhoneNumber,
                        Email = model.Email,
                        Gender = model.Gender,
                        BirthCountry = model.BirthCountry,
                        Occupation = model.Occupation,
                        CreatedDate = DateTime.Now,
                        IsDeleted = false,
                        Address = model.Address,
                        Code = _commonService.generateUserCode(model.Email)
                    };
                    var result = _studentInformationService.Add(data);

                    string guId = Guid.NewGuid().ToString();
                    EStudentLogin data1 = new EStudentLogin()
                    {
                        StudentId = result.Data.Id,
                        Email = model.Email,
                        Password = model.Password,
                        IsActive = false,
                        IsDeleted = false,
                        VerificationCode = guId,
                        LogInFailedCount = 0
                    };
                    var result1 = _studentLoginService.Add(data1);

                    ModelState.Clear();
                    MailCommon mail = new MailCommon();

                    var baseUrl = Request.Url.GetLeftPart(UriPartial.Authority);
                    var url = baseUrl + "/Student/LogIn/Index?guId=" + guId;

                    string mailLink = baseUrl + "/EmailTemplete/StudentSignUpEmailTemplete/Index?NewSignedUpEmail=" + data1.Email + "&link=" + url;
                    string mailBody = Common.CommonServices.GetTemplate(mailLink);

                    string senderEmail = WebConfigurationManager.AppSettings["GmailUserName"].ToString();
                    string senderPassword = WebConfigurationManager.AppSettings["GmailPassword"].ToString();

                    new Thread(() =>
                    {
                        mail.SendMail(data1.Email, "New Account Register", mailBody, senderEmail, senderPassword);
                        mail.SendMail("admin@pronaati.com.au", "New Account Register", mailBody, senderEmail, senderPassword);
                    }).Start();

                    ViewBag.Message = "An activation link has been sent to your email address.  Please click on it to activate your account !";

                    //string body = Common.CommonServices.GetTemplate(baseUrl + "/EmailTemplete/StudentSignUpEmailTemplete/Index?NewSignedUpEmail=" + data1.Email);

                    SetViewBagForCountries();
                    return View();
                }
            }
            SetViewBagForCountries();
            return View(model);
        }

        public static string GetTemplate(string link)
        {
            using (var myWebClient = new WebClient())
            {
                myWebClient.Headers["User-Agent"] = "MOZILLA/5.0 (WINDOWS NT 6.1; WOW64) APPLEWEBKIT/537.1 (KHTML, LIKE GECKO) CHROME/21.0.1180.75 SAFARI/537.1";

                string page = myWebClient.DownloadString(link);

                return page;
            }
        }
        private void SetViewBagForCountries()
        {
            var countries = _commonService.getCountryDropDown();
            ViewBag.Countries = new SelectList(countries, "CountryCode", "Country");
        }

    }
}

RTech.Demo/Areas/Student/Views/SignUp/Index.cshtml
@model RTech.Demo.Areas.Student.ViewModels.SignUpViewModel
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout_PTE.cshtml";
}

<!--  Start -->
@using (Html.BeginForm("Index", "SignUp", null, FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    <div class="uk-section uk-section-muted uk-flex uk-flex-middle uk-animation-fade" uk-height-viewport>
        <div class="uk-width-1-1">
            <div class="uk-container">
                <div class="uk-grid-margin uk-grid uk-grid-stack" uk-grid>

                    <div class="uk-width-1-2@m uk-align-center">
                        <div class="uk-margin  uk-margin-auto uk-card uk-card-default uk-card-body uk-box-shadow-large uk-border-radius-small">

                            @if (ViewBag.Message != null)
                            {
                                <div class="col-lg-12 text-success">
                                    @ViewBag.Message

                                </div>
                            }
                            <h3 class="uk-card-title uk-text-center">Sign Up</h3>
                            <hr class="uk-divider-icon">

                            <div class="uk-grid-small" uk-grid>

                                <div class="uk-width-1-2@s">
                                    @Html.TextBoxFor(model => model.FirstName, new { @class = "uk-input", @placeholder = "First Name" })
                                    @Html.ValidationMessageFor(model => model.FirstName, "", new { @class = "text-danger" })
                                </div>
                                <div class="uk-width-1-2@s">
                                    @Html.TextBoxFor(model => model.LastName, new { @class = "uk-input", @placeholder = "Last Name" })
                                    @Html.ValidationMessageFor(model => model.LastName, "", new { @class = "text-danger" })
                                </div>

                                <div class="uk-width-1-2@s">
                                    @Html.EnumDropDownListFor(model => model.Gender, new { @class = "uk-input" })
                                    @Html.ValidationMessageFor(model => model.Gender, "", new { @class = "text-danger" })
                                </div>

                                <div class="uk-width-1-2@s">
                                    <input class="uk-input" id="image" name="image" type="file" value="">
                                    @Html.ValidationMessageFor(model => model.ImageUrl, "", new { @class = "text-danger" })
                                </div>

                                <div class="uk-width-1-2@s">
                                    @Html.DropDownListFor(model => model.BirthCountry, (IEnumerable<SelectListItem>)ViewBag.countries, "Country Of Birth", new { @class = "uk-select" })
                                    @Html.ValidationMessageFor(model => model.BirthCountry, "", new { @class = "text-danger" })
                                </div>

                                <div class="uk-width-1-2@s">
                                    @Html.TextBoxFor(model => model.Occupation, new { @class = "uk-input", @placeholder = "Occupation" })
                                    @Html.ValidationMessageFor(model => model.Occupation, "", new { @class = "text-danger" })
                                </div>
                                <div class="uk-width-1-2@s">
                                    @Html.TextBoxFor(model => model.Address, new { @class = "uk-input", @placeholder = "Address" })
                                    @Html.ValidationMessageFor(model => model.Address, "", new { @class = "text-danger" })
                                </div>

                                <div class="uk-width-1-2@s">
                                    @Html.TextBoxFor(model => model.PhoneNumber, new { @class = "uk-input", @placeholder = "Contact Number" })
                                    @Html.ValidationMessageFor(model => model.PhoneNumber, "", new { @class = "text-danger" })
                                </div>

                                <div class="uk-width-1-1@s">
                                    @Html.TextBoxFor(model => model.Email, new { @class = "uk-input", @placeholder = "Email" })
                                    @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
                                </div>
                                <div class="uk-width-1-1@s">
                                    @Html.TextBoxFor(model => model.Password, new { @class = "uk-input", @placeholder = "Password", @type = "password" })
                                    @Html.ValidationMessageFor(model => model.Password, "", new { @class = "text-danger" })
                                </div>

                                <div class="uk-width-1-1@s">
                                    @Html.TextBoxFor(model => model.ConfirmPassword, new { @class = "uk-input", @placeholder = "Confirm Password", @type = "password" })
                                    @Html.ValidationMessageFor(model => model.ConfirmPassword, "", new { @class = "text-danger" })
                                </div>

                            </div>
                                <div class="uk-margin uk-text-center">
                                    <hr> <button type="submit" class="uk-button uk-button-primary " href="signup-success.php">Sign Up</button>
                                </div>



                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

}
<!--  End -->